# Generated by Django 2.1.7 on 2019-03-22 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('logo', models.ImageField(blank=True, upload_to='uploads/kehubu.Group.logo/%Y/%m/%d/', verbose_name='logo')),
                ('weighting', models.PositiveSmallIntegerField(default=0, verbose_name='weighting')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_kehubu_group_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMemberRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=32, verbose_name='rank')),
                ('weighting', models.PositiveSmallIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kehubu.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('remark_name', models.CharField(max_length=32, verbose_name='remark name')),
                ('description', models.TextField(verbose_name='description')),
                ('is_starred', models.NullBooleanField(verbose_name='is starred')),
                ('is_blocked', models.NullBooleanField(verbose_name='is blocked')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_kehubu_member_set', to='kehubu.Group')),
                ('inviter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inviter_kehubu_member_set', to=settings.AUTH_USER_MODEL)),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='kehubu.GroupMemberRank')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_kehubu_member_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MobileNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('number', models.CharField(max_length=13, unique=True, verbose_name='number')),
                ('is_verified', models.BooleanField(default=False, verbose_name='is verified')),
                ('verification_code', models.CharField(max_length=16, verbose_name='verification code')),
                ('verification_code_expired', models.DateTimeField(blank=True, null=True, verbose_name='verification code expired')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kehubu_mobilenumber_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('IdentityCard', 'Identity Card'), ('Passport', 'Passport')], default='IdentityCard', max_length=32, verbose_name='ID type')),
                ('id_number', models.CharField(max_length=32, verbose_name='ID number')),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('u', 'unknown')], default='u', max_length=1, verbose_name='gender')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='birthdate')),
                ('nickname', models.CharField(blank=True, max_length=24, verbose_name='nickname')),
                ('country', models.CharField(blank=True, max_length=32, verbose_name='country')),
                ('province', models.CharField(blank=True, max_length=32, verbose_name='province')),
                ('city', models.CharField(blank=True, max_length=32, verbose_name='city')),
                ('head_image', models.ImageField(blank=True, upload_to='uploads/kehubu.Profile.head_image/%Y/%m/%d/', verbose_name='head image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kehubu_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='member_kehubu_group_set', through='kehubu.Member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='groupmemberrank',
            unique_together={('group', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('creator', 'name')},
        ),
    ]
