# Generated by Django 2.1.7 on 2019-03-26 04:31

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('kehubu', '0003_group_member_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='member',
            name='remark_name',
            field=models.CharField(blank=True, max_length=32, verbose_name='remark name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
