# Generated by Django 2.1.7 on 2019-03-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kehubu', '0004_auto_20190326_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='group',
            name='member_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
