# Generated by Django 2.2 on 2019-04-09 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kehubu.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kehubu', '0006_group_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('code', models.CharField(default=kehubu.models.make_invitation_code, editable=False, max_length=6)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kehubu.Group')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter_kehubu_invitation_code_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
