# Generated by Django 2.2 on 2019-04-11 03:48

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kehubu', '0007_groupinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='uploads/kehubu.Group.logo/%Y/%m/%d/'),
        ),
    ]
