# Generated by Django 2.2 on 2019-04-12 02:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kehubu', '0009_auto_20190411_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=70, verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=1024, verbose_name='description')),
                ('is_visible', models.BooleanField(default=True, verbose_name='is visible')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kehubu.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupAlbumImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image', models.ImageField(upload_to='uploads/kehubu.GroupAlbumImage.image/%Y/%m/%d/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kehubu.GroupAlbum')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
