# Generated by Django 2.2 on 2019-04-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kehubu', '0011_groupchat'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('group', 'parent', 'name')},
        ),
    ]
