# Generated by Django 2.2 on 2019-04-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20190417_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='uploads/forum.Attachment.file/%Y/%m/%d/'),
        ),
    ]
