# Generated by Django 2.2 on 2019-04-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20190417_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='post_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='topic_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='post_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
